-- Table: public.tbl_carpark_aggregated

-- DROP TABLE IF EXISTS public.tbl_carpark_aggregated;

CREATE TABLE IF NOT EXISTS public.tbl_carpark_aggregated
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    address character varying(255) COLLATE pg_catalog."default",
    carparkno character varying(255) COLLATE pg_catalog."default",
    carparktype character varying(255) COLLATE pg_catalog."default",
    latitude character varying(255) COLLATE pg_catalog."default",
    longitude character varying(255) COLLATE pg_catalog."default",
    lotstype character varying(255) COLLATE pg_catalog."default",
    lotsavailable character varying(255) COLLATE pg_catalog."default",
    recordeddatetime timestamp(6) without time zone,
    totallots character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT tbl_carpark_aggregated_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.tbl_carpark_aggregated
    OWNER to postgres;