-- Table: public.tbl_rainfall_data

-- DROP TABLE IF EXISTS public.tbl_rainfall_data;

CREATE TABLE IF NOT EXISTS public.tbl_rainfall_data
(
    latitude numeric(38,2),
    longitude numeric(38,2),
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    recordeddatetime timestamp(6) without time zone,
    value bigint,
    areaname character varying(255) COLLATE pg_catalog."default",
    stationid character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT tbl_rainfall_data_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.tbl_rainfall_data
    OWNER to postgres;
	

--
-- TOC entry 4742 (class 2606 OID 16451)
-- Name: tbl_rainfall_data tbl_rainfall_data_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

--ALTER TABLE ONLY public.tbl_rainfall_data
    --ADD CONSTRAINT tbl_rainfall_data_pkey PRIMARY KEY (id);

--
-- TOC entry 4889 (class 0 OID 16445)
-- Dependencies: 218
-- Data for Name: tbl_rainfall_data; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.tbl_rainfall_data VALUES (1.38, 103.88, 1, '2025-04-27 20:35:00', 0, 'Yio Chu Kang Road', 'S219');
INSERT INTO public.tbl_rainfall_data VALUES (1.36, 103.85, 2, '2025-04-27 20:35:00', 0, 'Ang Mo Kio Avenue 10', 'S216');
INSERT INTO public.tbl_rainfall_data VALUES (1.35, 103.86, 3, '2025-04-27 20:35:00', 0, 'Bishan Street 13', 'S217');
INSERT INTO public.tbl_rainfall_data VALUES (1.30, 103.88, 4, '2025-04-27 20:35:00', 0, 'Tanjong Rhu', 'S214');
INSERT INTO public.tbl_rainfall_data VALUES (1.33, 103.89, 5, '2025-04-27 20:35:00', 0, 'Geylang East Central', 'S215');
INSERT INTO public.tbl_rainfall_data VALUES (1.32, 103.81, 6, '2025-04-27 20:35:00', 0, 'Coronation Walk', 'S213');
INSERT INTO public.tbl_rainfall_data VALUES (1.40, 103.91, 7, '2025-04-27 20:35:00', 0, 'Punggol Central', 'S81');
INSERT INTO public.tbl_rainfall_data VALUES (1.40, 103.79, 8, '2025-04-27 20:35:00', 0, 'Mandai Lake Road', 'S40');
INSERT INTO public.tbl_rainfall_data VALUES (1.34, 103.94, 9, '2025-04-27 20:35:00', 0, 'Simei Avenue', 'S84');
INSERT INTO public.tbl_rainfall_data VALUES (1.35, 103.68, 10, '2025-04-27 20:35:00', 0, 'Nanyang Avenue', 'S44');
INSERT INTO public.tbl_rainfall_data VALUES (1.34, 103.85, 11, '2025-04-27 20:35:00', 0, 'Toa Payoh North', 'S88');
INSERT INTO public.tbl_rainfall_data VALUES (1.34, 103.89, 12, '2025-04-27 20:35:00', 0, 'Kim Chuan Road', 'S43');
INSERT INTO public.tbl_rainfall_data VALUES (1.36, 103.89, 13, '2025-04-27 20:35:00', 0, 'Hougang Avenue 1', 'S221');
INSERT INTO public.tbl_rainfall_data VALUES (1.29, 103.82, 14, '2025-04-27 20:35:00', 0, 'Henderson Road', 'S222');
INSERT INTO public.tbl_rainfall_data VALUES (1.37, 103.83, 15, '2025-04-27 20:35:00', 0, 'Upper Thomson Road', 'S08');
INSERT INTO public.tbl_rainfall_data VALUES (1.34, 103.83, 16, '2025-04-27 20:35:00', 0, 'Lornie Road', 'S07');
INSERT INTO public.tbl_rainfall_data VALUES (1.39, 103.90, 17, '2025-04-27 20:35:00', 0, 'Compassvale Lane', 'S220');
INSERT INTO public.tbl_rainfall_data VALUES (1.31, 104.00, 18, '2025-04-27 20:35:00', 0, 'Changi East Close', 'S208');
INSERT INTO public.tbl_rainfall_data VALUES (1.29, 103.77, 19, '2025-04-27 20:35:00', 0, 'Pasir Panjang', 'S203');
INSERT INTO public.tbl_rainfall_data VALUES (1.32, 103.77, 20, '2025-04-27 20:35:00', 0, 'Clementi Park', 'S201');
INSERT INTO public.tbl_rainfall_data VALUES (1.32, 103.82, 21, '2025-04-27 20:35:00', 0, 'Bukit Timah Road', 'S90');
INSERT INTO public.tbl_rainfall_data VALUES (1.28, 103.79, 22, '2025-04-27 20:35:00', 1, 'South Buona Vista Road', 'S92');
INSERT INTO public.tbl_rainfall_data VALUES (1.42, 103.84, 23, '2025-04-27 20:35:00', 0, 'Yishun Ring Road', 'S209');
INSERT INTO public.tbl_rainfall_data VALUES (1.33, 103.78, 24, '2025-04-27 20:35:00', 0, 'Clementi Road', 'S50');
INSERT INTO public.tbl_rainfall_data VALUES (1.37, 103.95, 25, '2025-04-27 20:35:00', 0, 'Pasir Ris Street 51', 'S94');
INSERT INTO public.tbl_rainfall_data VALUES (1.44, 103.77, 26, '2025-04-27 20:35:00', 0, 'Woodlands Centre', 'S210');
INSERT INTO public.tbl_rainfall_data VALUES (1.43, 103.76, 27, '2025-04-27 20:35:00', 0, 'Kranji Road', 'S211');
INSERT INTO public.tbl_rainfall_data VALUES (1.30, 103.87, 28, '2025-04-27 20:35:00', 0, 'Nicoll Highway', 'S119');
INSERT INTO public.tbl_rainfall_data VALUES (1.26, 103.68, 29, '2025-04-27 20:35:00', 0, 'Banyan Road', 'S117');
INSERT INTO public.tbl_rainfall_data VALUES (1.29, 103.62, 30, '2025-04-27 20:35:00', 0, 'Tuas South Avenue 3', 'S115');
INSERT INTO public.tbl_rainfall_data VALUES (1.31, 103.91, 31, '2025-04-27 20:35:00', 0, 'Marine Parade Road', 'S113');
INSERT INTO public.tbl_rainfall_data VALUES (1.25, 103.83, 32, '2025-04-27 20:35:00', 0, 'Sentosa', 'S60');
INSERT INTO public.tbl_rainfall_data VALUES (1.38, 103.76, 33, '2025-04-27 20:35:00', 0, 'Bukit Panjang Road', 'S64');
INSERT INTO public.tbl_rainfall_data VALUES (1.44, 103.74, 34, '2025-04-27 20:35:00', 0, 'Kranji Way', 'S66');
INSERT INTO public.tbl_rainfall_data VALUES (1.37, 103.98, 35, '2025-04-27 20:35:00', 0, 'Upper Changi Road North', 'S24');
INSERT INTO public.tbl_rainfall_data VALUES (1.37, 103.81, 36, '2025-04-27 20:35:00', 0, 'Upper Peirce Reservoir Park', 'S69');
INSERT INTO public.tbl_rainfall_data VALUES (1.32, 103.86, 37, '2025-04-27 20:35:00', 0, 'Towner Road', 'S123');
INSERT INTO public.tbl_rainfall_data VALUES (1.39, 103.94, 38, '2025-04-27 20:35:00', 0, 'Pasir Ris Drive 12', 'S29');
INSERT INTO public.tbl_rainfall_data VALUES (1.37, 103.72, 39, '2025-04-27 20:35:00', 0, 'Old Choa Chu Kang Road', 'S121');
INSERT INTO public.tbl_rainfall_data VALUES (1.35, 103.72, 40, '2025-04-27 20:35:00', 0, 'Jurong West Street 42', 'S229');
INSERT INTO public.tbl_rainfall_data VALUES (1.41, 103.87, 41, '2025-04-27 20:35:00', 0, 'Seletar Aerospace View', 'S900');
INSERT INTO public.tbl_rainfall_data VALUES (1.42, 103.97, 42, '2025-04-27 20:35:00', 0, 'Pulau Ubin', 'S106');
INSERT INTO public.tbl_rainfall_data VALUES (1.44, 103.80, 43, '2025-04-27 20:35:00', 0, 'Woodlands Drive 62', 'S227');
INSERT INTO public.tbl_rainfall_data VALUES (1.31, 103.96, 44, '2025-04-27 20:35:00', 0, 'East Coast Parkway', 'S107');
INSERT INTO public.tbl_rainfall_data VALUES (1.35, 103.70, 45, '2025-04-27 20:35:00', 0, 'Jurong West Street 73', 'S228');
INSERT INTO public.tbl_rainfall_data VALUES (1.44, 103.79, 46, '2025-04-27 20:35:00', 0, 'Woodlands Avenue 9', 'S104');
INSERT INTO public.tbl_rainfall_data VALUES (1.27, 103.80, 47, '2025-04-27 20:35:00', 0, 'Malan Road', 'S226');
INSERT INTO public.tbl_rainfall_data VALUES (1.19, 103.77, 48, '2025-04-27 20:35:00', 0, 'Semakau Landfill', 'S102');
INSERT INTO public.tbl_rainfall_data VALUES (1.30, 103.80, 49, '2025-04-27 20:35:00', 0, 'Margaret Drive', 'S223');
INSERT INTO public.tbl_rainfall_data VALUES (1.34, 103.98, 50, '2025-04-27 20:35:00', 0, 'Airport Boulevard', 'S224');
INSERT INTO public.tbl_rainfall_data VALUES (1.29, 103.78, 51, '2025-04-27 20:35:00', 0, 'Kent Ridge Road', 'S71');
INSERT INTO public.tbl_rainfall_data VALUES (1.31, 103.71, 52, '2025-04-27 20:35:00', 0, 'Jurong Pier Road', 'S33');
INSERT INTO public.tbl_rainfall_data VALUES (1.29, 103.81, 53, '2025-04-27 20:35:00', 1, 'Alexandra Road', 'S77');
INSERT INTO public.tbl_rainfall_data VALUES (1.30, 103.84, 54, '2025-04-27 20:35:00', 0, 'Somerset Road', 'S79');
INSERT INTO public.tbl_rainfall_data VALUES (1.31, 103.89, 55, '2025-04-27 20:35:00', 0, 'Poole Road', 'S78');
INSERT INTO public.tbl_rainfall_data VALUES (1.31, 103.84, 56, '2025-04-27 20:35:00', 0, 'Scotts Road', 'S111');
INSERT INTO public.tbl_rainfall_data VALUES (1.44, 103.70, 57, '2025-04-27 20:35:00', 0, 'Lim Chu Kang Road', 'S112');
INSERT INTO public.tbl_rainfall_data VALUES (1.30, 103.76, 58, '2025-04-27 20:35:00', 0, 'West Coast Road', 'S230');
